### PR TITLE
LocalIO code completely reviewed (#2)

### PR DESCRIPTION
**Pull request by ribico**
added helper functions to reduce duplicate code
modification done keeping in mind retro-compatibility
the code compiles but is not tested

### CODE REVIEW

**Comment by ribico** [comment]
These are the changed methods, check if tested:
- [x] `Souliss_DigIn` used in board [ROW1B3](https://github.com/ribico/gr-home-automation/blob/ef90090e9ca061f66446fa873db9e6cd0acd1023/node03_ROW1B3/node03_ROW1B3.ino)
- [x] `Souliss_LowDigIn` used in board [LOFTB1](https://github.com/ribico/gr-home-automation/blob/17e82134bfd7dfa07cdeb28ee94216ca7a7852ca/node00_LOFTB1/node00_LOFTB1.ino)
- [ ] `Souliss_DigIn2State` not used
- [ ] `Souliss_LowDigIn2State` not used
- [x] `Souliss_DigInHold` used in board [ROW2B2](https://github.com/ribico/gr-home-automation/blob/ef90090e9ca061f66446fa873db9e6cd0acd1023/node06_ROW2B2/node06_ROW2B2.ino)
- [ ] `Souliss_LowDigInHold` not used
- [ ] `Souliss_DigKeepHold` not used
- [ ] `Souliss_LowDigKeepHold` not used
- [x] `Souliss_DigOut` used in board [ROW1B4](https://github.com/ribico/gr-home-automation/blob/7e4096446ea64d505e8433bd83af517c3c3f186c/node04_ROW1B4/node04_ROW1B4.ino)
- [x] `Souliss_LowDigOut` used in board [GTW1B1](https://github.com/ribico/gr-home-automation/blob/ef90090e9ca061f66446fa873db9e6cd0acd1023/node13_GTW1B1/node13_GTW1B1.ino)
- [ ] `Souliss_PulseDigOut` not used
- [ ] `Souliss_PulseLowDigOut`not used
- [x] `Souliss_nDigOut`used in board [GARDB1](https://github.com/ribico/gr-home-automation/blob/7e4096446ea64d505e8433bd83af517c3c3f186c/node15_GARDB1/node15_GARDB1.ino)
- [x] `Souliss_nLowDigOut` used in board [LOFTB1](https://github.com/ribico/gr-home-automation/blob/17e82134bfd7dfa07cdeb28ee94216ca7a7852ca/node00_LOFTB1/node00_LOFTB1.ino)
- [x] `Souliss_DigInHoldSteps` used in board [ROW1B4](https://github.com/ribico/gr-home-automation/blob/7e4096446ea64d505e8433bd83af517c3c3f186c/node04_ROW1B4/node04_ROW1B4.ino)
- [ ] `Souliss_LowDigInHoldSteps` not used

**Comment by plinioseniore** [comment]
@ribico thanks, please notify me here once all checks has been completed.

**Comment by ribico** [comment]
All tested (at least all I could test in my network).
I just have a doubt on LowDigIn because I see a slightly different behavior than before.
It seems that input filtering is not working or not working as good as before... I couldn't see the issue from a quick code analysis.
I need to investigate a bit further.

**Comment by ribico** [comment]
This last fix solves the the issue I experienced with SApp (DB + UI feedback) and push button filtering.
I think we can consider this branch tested and working now.

**Pull request merged**
