### PR TITLE
Updated T31 to work as expected by US-American and Canadian HVAC systems

### PR DESCRIPTION
**Pull request by stefanst**

### CODE REVIEW

**Comment by plinioseniore** [comment]
@fazioa could you please have a look and approve the merge?

**Comment by plinioseniore** [comment]
@fazioa I've merged the contribution by @stefanst into a dedicated branch of the main repository called stefanst-souliss, please let me know once you get the opportunity to test it out so that we can include it for the next release.

https://github.com/souliss/souliss/tree/stefanst-souliss

**Comment by fazioa** [comment]
Tested on prototipe of thermostat and it work fine.
I tested only setpoint and relè, not for fan function

I don't like at base/T3n.cpp, line 134. [....&& (in_temp > 1)]
The code test that temperature is >1 but what happens if T31 is used for other application where the temperature is around zero?

**Comment by stefanst** [comment]
in_temp>1 is necessary for DALLAS sensor. Sometimes when updating setpoint, or switching fan etc. from openhab or android app, dallas sensor reports 0 degrees. This causes logics to come on or turn off briefly which is not desirable.
After unsuccessful search for the cause for the 0 reading from dallas sensor, I decided to prevent it with the  in_temp>1 condition.

**Comment by fazioa** [comment]
I have same problem with DHT22.

**Comment by plinioseniore** [comment]
There is a known problem with handling of zero values that is supposed to
be solved with 7.1.1 (at least from the math point of view it works now).

I will merge the stefanst-souliss branch in patch-7.1.1 so that you could
test the benefit of the changes in the handling of zero values and then the
revised T31 will be public with 7.1.1.

**Comment by juanpintom** [comment]
I still having problems with T31 on this
https://github.com/souliss/souliss/issues/175#issuecomment-150041385

Any hint?

Regards

2015-10-28 7:44 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
Have you tried the stefan branch?

**Comment by juanpintom** [comment]
Yes, I tried a few days ago with the same result, this loop that freezes
the node, you can see on the comments at issue posted before.

Regards

2015-10-28 20:33 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by mcbittech** [comment]
For me the same results.
Only a reset can save the node

Flavio.
Il 28/ott/2015 20:33, "Dario Di Maio" notifications@github.com ha scritto:

**Comment by plinioseniore** [comment]
I've merged the stefan branch into the patch7.1.1

**Comment by plinioseniore** [comment]
@stefanst any hint on problem highlighted by @juanpintom and @mcbittech ?

**Comment by stefanst** [comment]
No idea what's happening there. I don't currently understand enough about the vnet protocol to be much help. I didn't see anything in the original code either, that would make me expect this type behavior. 
Is my assumption correct that the traffic is generated every time that

i_trigger == Souliss_TRIGGED  ?

That would give me something to search for.

**Comment by plinioseniore** [comment]
Yes it is, it communicate only when something is changing.

**Pull request merged**
