### PR TITLE
Eliminate warnings

### PR DESCRIPTION
**Pull request by dgolda**
Small fixes to eliminate warnings found while compiling in Eclipse.

### CODE REVIEW

**Comment by plinioseniore** [comment]
@dgolda I've tried once in the [past](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/souliss/SBG4mq_FbFY/ii_ZLIesc3IJ) and the result was a strange behavior of oFrame with some network architectures with bridges.

So I'm bit worried about this merge, even because we should add return 0; in all the function that doesn't when are supposed to return something.

Could you please tell me if in your architecture you have a bridge like ethernet(gateway)-ethernet/rs485(supernode/bridge)-rs485? Even nRF24 is ok.

**Comment by dgolda** [comment]
I have not tested these changes with bridge, so if you think it's dangerous, please revert it.

I've played with compiler and found, that when no explicit return value is given, that function returns some random value - in my case it was always "3".

My sketch:

```
// Configure the framework
#include "bconf/StandardArduino.h"          // Use a standard Arduino
#include "conf/ethW5100.h"                  // Ethernet through Wiznet W5100
#include "conf/Gateway.h"                   // The main node is the Gateway, we have just one node
#include "conf/Webhook.h"                   // Enable DHCP and DNS

// Include framework code and libraries
#include <SPI.h>

/*** All configuration includes should be above this line ***/ 
#include "Souliss.h"

void setup() {
  Serial.begin(115200);
}

U8 testOriginal(void* a, U8 b) {
  Serial.print(a != NULL);
  Serial.print(",");
  Serial.print(b);
  Serial.print(" = ");
  // If a frame is defined
  if (a)
    if (b)
      return 1;
    else
      return 0;
}

U8 testFixed(void*  a, U8 b) {
  Serial.print(a != NULL);
  Serial.print(",");
  Serial.print(b);
  Serial.print(" = ");
  if (a) {
    if (b)
      return 1;
    else
      return 0;
  } else {
    return 13;
  }
}

U8 testNoReturn(U8 arg) {
  Serial.print(arg);
  Serial.print(" = ");
  if (arg) {
    return 17;
  }
}

void loop() {
  Serial.println("before:");
  U8 result;
  void* some = &result;
  result = testOriginal(NULL, 0);
  Serial.println(result);

  result = testOriginal(NULL, 1);
  Serial.println(result);

  result = testOriginal(some, 0);
  Serial.println(result);

  result = testOriginal(some, 1);
  Serial.println(result);

  Serial.println("after:");

  result = testFixed(NULL, 0);
  Serial.println(result);

  result = testFixed(NULL, 1);
  Serial.println(result);

  result = testFixed(some, 0);
  Serial.println(result);

  result = testFixed(some, 1);
  Serial.println(result);

  Serial.println("test1:");

  result = testNoReturn(1);
  Serial.println(result);
  result = testNoReturn(0);
  Serial.println(result);

  delay(10000);
}
```

and result:

```
before:
0,0 = 3
0,1 = 3
1,0 = 0
1,1 = 1
after:
0,0 = 13
0,1 = 13
1,0 = 0
1,1 = 1
test1:
1 = 17
0 = 3
```

**Comment by plinioseniore** [comment]
I think that the safest option is to include your changes out of the oFrame
ones, adding return values in case of none of the condition catched and
keep it into a dedicated branch for a while.

Dario.

**Comment by plinioseniore** [comment]
@dgolda I've included all your changes out of the ones at oFrame, are available into a dedicated branch that I would kindly ask you to try and test
https://github.com/souliss/souliss/tree/pr-eliminate-warnings

Let me know if it works as expected.

**Pull request closed without merging**
