### PR TITLE
Continuous Integration using @PlatformIO and @travis-ci

### PR DESCRIPTION
**Pull request by ivankravets**
See result: https://travis-ci.org/souliss/souliss/builds/94723971

Official Travis CI Documentation for @PlatformIO: https://docs.travis-ci.com/user/integration/platformio/

### CODE REVIEW

**Comment by plinioseniore** [comment]
Hi @ivankravets what's the benefit of Platformio? Had not yet the opportunity to have a try. I see that you didn't setup any core for ESP8266, is it embed by default?

**Comment by ivankravets** [comment]
Hi @plinioseniore,
1. Each example is in separate job
2. Up-to-date stable toolchains, frameworks
3. Support for [more then 150 embedded boards](http://platformio.org/) via `platformio ci --board ***` option
4. Easy to read and edit  `.travis.yml`.

> I see that you didn't setup any core for ESP8266, is it embed by default?

PlatformIO installs it automatically according to board settings. Please visit our official site for details http://platformio.org.

P.S: We have users who use your library. However, we have one issue with compiler logic. See https://github.com/platformio/platformio/issues/298 . Nevertheless, the behaviour of PlatformIO cross-platform builder will be improved in PlatformIO 3.0.

Regards, Ivan.

**Comment by plinioseniore** [comment]
Hi Ivan,

yep, as stated in that issue, the Arduino IDE is designed to work without
MAKEFILE and allow the use of a single folder. This doesn't fit for
Souliss, that has too many files for a single folder.

Same problems arise with Eclipse or any other IDE that isn't the Arduino
one.

The new .travis.yml based on Platformio is not passing the building, any
suggestion?

Dario.

From Mobile.

**Comment by ivankravets** [comment]
Sure, PlatformIO doesn't build `*.c/*.cpp` files from your library. I've just passed it to C Preprocessor includes list. See https://github.com/ivankravets/souliss/blob/friariello/.travis.yml#L75

**Comment by plinioseniore** [comment]
Some jobs fails because we doesn't use stable ESP8266 cores but staging
ones (you can see the core release in previous .travis)

https://travis-ci.org/souliss/souliss/jobs/94724006

Some others because there are missing dependecies and was skipped in
previous .travis.yml

From Mobile.

**Comment by ivankravets** [comment]
How about this example? https://travis-ci.org/souliss/souliss/jobs/94724016

**Comment by ivankravets** [comment]
See updated build https://travis-ci.org/souliss/souliss/builds/94836311

The latest question is for https://travis-ci.org/souliss/souliss/jobs/94836362

**Comment by plinioseniore** [comment]
@ivankravets from my point of view, I will keep the continuous integration through the Arduino IDE because is the tool the most of the users will use, so this ensure that code is properly compiled. More I have more control on used cores, that's important with ESP8266 that updates his cores very quickly.

On the otherside Platformio is the tool for more skilled peoples, so we have two ways:
1) Include a script for platformio, so that people can fork and use that one for their own builds
2) Create a general tutorial that explain how use Platformio with Souliss (and generally for code thinked to be compiled by the Arduino IDE).

I think that @bcelary can help on this, has he is using Platformio.

**Comment by bcelary** [comment]
@ivankravets it might be actually a good idea to include a setting in Platformio which tries to mimic Arduino IDE builder. It could be an option for the 'init' mode and/or a dedicated setting. The user could just enable such behavior on demand without any other tweaks. I guess it could be a really good selling point for the users fed up with Arduino IDE to switch to Platformio.

@plinioseniore since my build env is up and running I was not touching it much, so I don't see myself as an experienced user TBH.

**Comment by ivankravets** [comment]
@plinioseniore thanks a lot for your point. I understand you.

I don't know where to put information how to use @PlatformIO with @Souliss. I'll explain these steps here:
- Install [PlatformIO](http://platformio.org) 
- Initialise new project

``` shell
# create new folder for it
mkdir myproject
cd myproject

# full list with boards http://platformio.org/#!/boards
platformio init --board uno --b esp01
```
- Temporary hook for PlatformIO 2.0. Edit `myproject/platformio.ini` (will be created with the step above) and add to each environment `[env:***]` these lines

```
build_flags = -I${LIBSOURCE_DIRS[1]}/souliss
lib_ignore = souliss
```
- Place your source code to `myproject/src` directory
- Install Souliss library http://platformio.org/#!/lib/show/543/souliss

``` shell
platformio lib install 543
```
- Process project and firmwares will be uploaded to the specified boards

``` shell
platformio run --target upload
```

Don't need to install Java or additional software. The only one requirement is Python Interpreter. These steps are the same for all popular host OS (Mac OS, Windows, Linux 32/64 & Linux ARMv6+)

**Comment by plinioseniore** [comment]
@ivankravets could you please add these instructions as tutorial following the below guide?https://github.com/souliss/souliss.github.io/blob/master/README.md

You just need to fork the repository and include your contents, in the README there is the picture resolution and the folder where tutorial/blogpost are placed.

Thanks.

**Comment by plinioseniore** [comment]
I suggest to use to tutorial to make clear the strongness of platformio.

**Pull request closed without merging**
