### PR TITLE
Prevent infinite loop while serving a new dynamic address

### PR DESCRIPTION
**Pull request by alvarolobato**

### CODE REVIEW

**Comment by plinioseniore** [comment]
Hi @alvarolobato,

I was looking at the code, wondering why there is a nested do-for. Seems that as is written now and before, it just behave as a simple for.

So, I start looking for previous commit to understand why the code has been written that way, then I found this [Fix for a possible infinite loop commit](https://github.com/souliss/souliss/commit/72ce9b2719f9825141f0ed57a90795fb6defea2b) dated 2015. This is exactly the same change that you did, but later has been discarded.

I will investigate, in the while any suggestion is apprecciated. Have you tested your modified code running with addresses assigned dynamically?

Thanks,
Dario.

**Comment by plinioseniore** [comment]
Never mind, there was two pieces of code similar and I didn't recognize that the fix of 2015 was only on one of those two.

The nested do-for is used to check the next address is case of conflict.

**Comment by plinioseniore** [comment]
Merged.

**Comment by alvarolobato** [comment]
Thanks Dario. Yes I've tested on my gateway and works fine.

**Pull request merged**
