### PR TITLE
Fixed color order in e04_RGBStrip.ino

### PR DESCRIPTION
**Pull request by marcolino7**
Fixed color order in e04_RGBStrip.ino

### CODE REVIEW

**Comment by plinioseniore** [comment]
Ciao Marco, is generally RGB why you changed the order as BGR?

**Comment by marcolino7** [comment]
Because in this way working. Leaving order in RGB red and blue are switched
between them. I don't know why. First slot correspond to blue and not to
red
Il 28/Ott/2015 07:52, "Dario Di Maio" notifications@github.com ha scritto:

**Comment by plinioseniore** [comment]
You should switch the pins instead, let me know.

**Comment by marcolino7** [comment]
HI Perhaps is better to leave RGB Color in right order.
If you want tou should only fix example on the blog:
http://souliss.net/articles/esp8266-in-commercial-product/
In this case Red and Blue must be switched or must be switch the pin.
I close this

**Comment by plinioseniore** [comment]
Yes please, switch the pins in the blig post.

Dario.

From Mobile.

**Comment by marcolino7** [comment]
Ho Dario,
sorry for asking, but I never do that. How can I access to blog post?
Regards
Marco

**Comment by marcolino7** [comment]
HI Dario,
got it how to do. In next day I'll fix it.
Regards

Marco

**Pull request closed without merging**
