### PR TITLE
RAM Optimization on Debug

### PR DESCRIPTION
**Pull request by juanpintom**
Change every Serial.print("const string") with Serial.print(F("const string")); To use less RAM on debug. Helloworld_uip not compiles on Arduino Uno with debug enabled.

Reference to the function:
https://www.baldengineer.com/arduino-f-macro.html

### CODE REVIEW

**Comment by plinioseniore** [comment]
Could you please compare the usage of RAM / FLASH with and without your patch? I'm worried that we save RAM but end-up with no FLASH available.

Is this modification compatible with ESP8266?

**Comment by juanpintom** [comment]
I'll do, we are working on Spanish forum and I opened a post on english ML
to discurs it, that is why I don't commited the pull request.

Regards :)

2015-06-23 16:11 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by juanpintom** [comment]
With the actual vNet file: (not uploadable)
Sketch uses 20.956 bytes (64%) of program storage space. Maximum is 32.256 bytes.
Global variables use 2.108 bytes (102%) of dynamic memory, leaving -60 bytes for local variables. Maximum is 2.048 bytes.

And with vNet file modified: 
Sketch uses 21.130 bytes (65%) of program storage space. Maximum is 32.256 bytes.
Global variables use 1.842 bytes (89%) of dynamic memory, leaving 206 bytes for local variables. Maximum is 2.048 bytes.

I don't tested if works on ESP but with modified file compile ok.

Regards

**Comment by plinioseniore** [comment]
Can you please check support for F() on ESP8266 Arduino cores?

**Comment by juanpintom** [comment]
I received today 2 ESP12E and their boards, I'll test it soon, for now I tried to compile and seems to be ok.

**Comment by plinioseniore** [comment]
Any news on this topic? We may also find a way, using C macro, to avoid the F() for ESP8266.

**Comment by juanpintom** [comment]
I need a day or two to confirm F() is working on ESP, meanwhile I founded this paragraph on esp8266 Arduino Github:

Progmem

The Program memory features work much the same way as on a regular Arduino; placing read only data and strings in read only memory and freeing heap for your application. The important difference is that on the esp8266 the literal strings are not pooled. This means that the same literal string defined inside a F("") and/or PSTR("") will take up space for each instance in the code. So you will need to manage the duplicate strings yourself.

From: https://github.com/esp8266/Arduino

**Comment by juanpintom** [comment]
Tested and working on ESP :)

Regards

**Comment by plinioseniore** [comment]
That's great, may you please apply the change for all the logs (vNet,
MaCaco, Souliss, uIP, ...)?

**Comment by juanpintom** [comment]
There are a lot of LOG's :S xD
I maded some changes, can you take a look?  

I searched for more LOG's, with time I can change every static string.

I made a mistake on my pull-request, I don't know how to solve, it gives and option to do it with git commands but I don't have access to a command line now. Can you help me? // Sorry, I have problems to understand Git :S

Regards

**Comment by plinioseniore** [comment]
Probably the best is use the F() on the main define. I will have a look and
let you know.

Dario.

From Mobile.

**Comment by juanpintom** [comment]
Not, it isn't, the F("") function cannot be used to show variables, just static strings. Look at the link on the first comment:
https://www.baldengineer.com/arduino-f-macro.html

Regards

**Comment by juanpintom** [comment]
The files on this branch and on 1 - 1 can be merged

**Comment by plinioseniore** [comment]
Juan coul you please include also logs for all others?
https://github.com/souliss/souliss/wiki/TroubleShootSouliss

An easy way to catch them all is to use Notepad++, then you use the Search in Files option for
MaCaco_DEBUG, UIP_LOGGING, MODBUS_DEBUG, XMLSERVER_DEBUG and it will show you where those are used, so that you can update them easily.

Once ready we will merge them all.

**Comment by juanpintom** [comment]
I'll do next week :P

Regards

2015-07-04 10:37 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
I'm starting to merge this one, because the mods are actually on two different branches that cannot be merged.

**Pull request merged**
