### PR TITLE
hostname configurable in the sketch

### PR DESCRIPTION
**Pull request by imero-dev**
For setting the hostname in your sketch you can use:
# define HOST_NAME_INSKETCH
# define HOST_NAME "YourHostName"

### CODE REVIEW

**Comment by marcolino7** [comment]
I just tried in the past, but does not work,
Did you tried it?

Regards

**Comment by juanpintom** [comment]
Im working to configure this on the webinterface, I'll make a commit on my github in a while.

**Comment by imero-dev** [comment]
Yes I tried it and works, in the arduino IDE shows the hostname assigned in sketch

I was testing github, I do many changes to the code offline, but and I'm trying to use this to start to help you.

**Comment by marcolino7** [comment]
I'll try in next days. Hope @plinioseniore  will merge into souliss

thankls

**Comment by plinioseniore** [comment]
Merged, thanks.

**Pull request merged**
