### PR TITLE
New lastin fix compilation error

### PR DESCRIPTION
**Pull request by ribico**

### CODE REVIEW

**Comment by plinioseniore** [comment]
@ribico there is nothing here https://github.com/souliss/souliss/pull/227/files

is this pull request an error?

**Comment by ribico** [comment]
I have no idea why it doesn't show the changed file..
anyway these are the small modifications I have made:
https://github.com/ribico/souliss/commit/b65b2d16642305a6a01d9ae1e230cc7b758d00af

**Comment by ribico** [comment]
ohh, I see.. it included also a commit revert.
Not sure why I have done it.

**Comment by plinioseniore** [comment]
I'm closing this, request a new pull please.

**Pull request closed without merging**
