### PR TITLE
Incongruence in T21 output state

### PR DESCRIPTION
**Pull request by fazioa**
It work for me!
SoulissApp don't show correctly all T21 and T22 states.
Tested with beta of binding for Openhab 2

### CODE REVIEW

**Comment by fazioa** [comment]
e03 - Typicals examples on Expressif ESP8266

**Comment by plinioseniore** [comment]
@FulvioSpelta is the king of T2x, Fulvio could you please have a look?

**Comment by FulvioSpelta** [comment]
Hi all
as in  #291 comments:

> the constants Souliss_T2n_LimSwitch_Close and Souliss_T2n_LimSwitch_Open are used as "input only" and shouldn't never go to the output.

I think that the suggested code change is not correct.
I'll do a code review for T21 and T22 in the weekend.

@fazioa what is the problem that you are facing ?

**Comment by fazioa** [comment]
Ok.
Then error is in 
https://github.com/souliss/souliss/blob/friariello/base/T2n.cpp#L126

Correct is...
FROM
memory_map[MaCaco_OUT_s + slot] = Souliss_T2n_LimSwitch_Open;			// Open Limit Switch

TO
memory_map[MaCaco_OUT_s + slot] = Souliss_T2n_State_Open;			// Open Limit Switch

**Comment by FulvioSpelta** [comment]
Yes I agree.

**Comment by plinioseniore** [comment]
Is there any change to apply to T2n.ccp?

**Comment by plinioseniore** [comment]
@fazioa The repository hasn't merged those changes. Is there anything that needs to be updated?

Thanks.

**Pull request closed without merging**
