### PR TITLE
LocalIO code completely reviewed 

### PR DESCRIPTION
**Pull request by ribico**
added helper functions to reduce duplicate code
modification done keeping in mind retro-compatibility
the code compiles but is not tested

### CODE REVIEW

**Comment by plinioseniore** [comment]
Hi Gabriele, not all examples are compiling, see tge details on the CI. Please review the code and push your code into a dedicated branch, so that we can merge it once has been tested.
https://travis-ci.org/souliss/souliss/builds/126241206

**Comment by ribico** [comment]
Compiling issue solved, it was just a function definition error
I have not enough rights to create a new branch on souliss/souliss and I also think that this modification could be really tested only if we include it this branch and not in a separate one.

Please tell me if you wish to create a new branch for this modification or include it here, the code is ready for a new PR now.

**Comment by yasserhabh** [comment]
Hello every one. i am Yasir student from Iraq . i have small project to make simple smart home system using Arduino and IoT . and i see souliss is very good platform for make it. but my problem i am not good in programming and i dont understand how i put T8,T16 and so on . if any one can help me in my situation. and if any one can discuss to me to understand how i program it
i have 
Arduino Mega2560 + ethernet W5100
8 chaneel relay board
2 Pir motion sensor 1 for auto light. 1 for alarm
2 photoresistor 1 for auto light 
buzzer for alarm
leds multi colors 
big thanks for anyone can help me or not. 
accept my best regards
Yasir Habh

**Comment by yasserhabh** [comment]
Hello every one. i am Yasir student from Iraq . i have small project to make simple smart home system using Arduino and IoT . and i see souliss is very good platform for make it. but my problem i am not good in programming and i dont understand how i put T8,T16 and so on . if any one can help me in my situation. and if any one can discuss to me to understand how i program it
i have 
Arduino Mega2560 + ethernet W5100
8 chaneel relay board
2 Pir motion sensor 1 for auto light. 1 for alarm
2 photoresistor 1 for auto light 
buzzer for alarm
leds multi colors 
big thanks for anyone can help me or not. 
accept my best regards
Yasir Habh

**Comment by ribico** [comment]
Hello Yasir,
you may find better help from the google groups thread
https://groups.google.com/forum/#!forum/souliss
This discussion is just for souliss developers.

Anyway you could start from the following resources:
https://github.com/souliss/souliss/wiki/Getting%20Started%20with%20Souliss
https://github.com/souliss/souliss/tree/friariello/examples/ethernet

**Pull request closed without merging**
