### PR TITLE
Sandaloecalzino

### PR DESCRIPTION
**Pull request by FulvioSpelta**
Added Controllino Ethernet Exmaples

### CODE REVIEW

**Comment by plinioseniore** [comment]
Where the #define for the Controllino pins are?

I don't know if include examples for Controllino is the right way, because we are starting to have too many example and this became a maintenance nightmare. Probably it would be better to provide  a tutorial that explains how to change and existing example to run on Controllino, because is really a matter of few lines of code compared to standard Ethernet examples.

**Comment by FulvioSpelta** [comment]
Where the #define for the Controllino pins are?

They are defined in the controllino.h file that is included at top of the sktech.

I need these examples in order to test our development, we can use them as we want.
I think that, they show clearly how to setup the "#include" needed, we can explain this in a tutorial, no problem. Should I remove them from the branch ?

**Comment by plinioseniore** [comment]
For now keep them, we will think it about once we will merge it into the main branch. I'm thinking that there is no real need to use the Controllino "cores" because are basically empty. We could include the #define by our self using same names as per DINo and other examples, so that run a Controllino will only require change the header include.

**Comment by plinioseniore** [comment]
Just added support for RS485 and the pin mapping file (to be filled)
https://github.com/souliss/souliss/commit/d33b0762092cfdd8e082d4bb9d162e88c7a2c1d2

I've not really got the pin mapping, at a quick read looks to have only Digital Outputs and just two Digital Inputs, looks strange.

Please fill in the hardware/SGTronic/ControllinoMaxi.h keeping the same style INn, OUTn, RELAYn so that we can easily use DINo sketches and avoid to have dedicated one for Controllino.

**Pull request merged**
